version: '3.8'

services:
  image_service:
    build:
      context: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/src/
    command: npm run start:dev

  database:
    image: mongo:3.6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    expose:
      - 27017

volumes:
  data: {}